language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - git clone https://github.com/elastic/logstash.git
  - cd ./logstash
  - ./gradlew clean assemble
  - export LOGSTASH_CORE_PATH=$PWD/logstash-core
  - cd ../

script:
  - echo "LOGSTASH_CORE_PATH=$LOGSTASH_CORE_PATH" >> gradle.properties
  - ./gradlew clean gem